# Generated by Django 4.0.4 on 2022-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
