# Generated by Django 4.0.4 on 2022-05-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_alter_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
